# Generated by Django 2.1.2 on 2020-02-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date_traded', models.DateField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Return14Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date_traded', models.DateField(blank=True, null=True)),
                ('latest_close', models.FloatField(blank=True, null=True)),
                ('prior_close', models.FloatField(blank=True, null=True)),
                ('return_percentage', models.FloatField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'return_14_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Return1Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date_traded', models.DateField(blank=True, null=True)),
                ('latest_close', models.FloatField(blank=True, null=True)),
                ('prior_close', models.FloatField(blank=True, null=True)),
                ('return_percentage', models.FloatField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'return_1_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Return30Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date_traded', models.DateField(blank=True, null=True)),
                ('latest_close', models.FloatField(blank=True, null=True)),
                ('prior_close', models.FloatField(blank=True, null=True)),
                ('return_percentage', models.FloatField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'return_30_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Return7Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date_traded', models.DateField(blank=True, null=True)),
                ('latest_close', models.FloatField(blank=True, null=True)),
                ('prior_close', models.FloatField(blank=True, null=True)),
                ('return_percentage', models.FloatField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'return_7_day',
                'managed': False,
            },
        ),
    ]
