# Generated by Django 2.1.2 on 2020-02-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('marketcap', models.BigIntegerField(blank=True, db_column='marketCap', null=True)),
                ('shortname', models.TextField(blank=True, db_column='shortName', null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stockinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('open', models.FloatField(blank=True, db_column='Open', null=True)),
                ('high', models.FloatField(blank=True, db_column='High', null=True)),
                ('low', models.FloatField(blank=True, db_column='Low', null=True)),
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('volume', models.FloatField(blank=True, db_column='Volume', null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_price_history',
                'managed': False,
            },
        ),
    ]
